config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do
        get 'price_fetch'
        get 'process_order'
      end
    end
  resources :products do
    member do
    get 'mapping'
    post 'mapping_create'
    patch "mapping_create"
  end
end

  resources :categories

  root 'categories#home_page'

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end
  def price_fetch
    begin
      id=params[:id]
      a=Product.find(id)
      respond_to do |format|
         format.json {
        render json: {:responce => "Success",:product => a}
         }
           end
    rescue =>err
      
     respond_to do |format|
         format.json {
        render json: {:responce => "Error"}
         }
           end
     
    end
  end
  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :index, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 

  def process_order
    # begin
        data=Order.all.where(:status => "Unprocessed",:reason => nil).order("created_at")
        data.each do |t|
          a=Product.find(t.product_id)
          if a.quantity>=t.quantity
            a.quantity=a.quantity-t.quantity
            a.save
            Order.where(:id => t.id).first.update(:status => "Processed",:sold_quantity => t.quantity ,:sold_total_price => t.total_price)
          elsif a.quantity!=0
            quantity=a.quantity
            left_quantity=t.quantity-a.quantity
            a.quantity=0
            a.save
            total_price=t.price * quantity
            Order.where(:id => t.id).first.update(:status => "Partially Processed",:sold_quantity => quantity ,:sold_total_price => total_price,:reason => "Insufficient quantity")
          else
            Order.where(:id => t.id).first.update(:status => "Cannot be Processed",:reason => "Insufficient quantity")
          end
        end
        respond_to do |format|
            format.html { redirect_to orders_path, notice: 'Order was successfully processed.' }
            format.json { render :index, status: :created, location: @order }
         
        end
  #   rescue => err
  #     respond_to do |format|
  #        format.html { redirect_to orders_path, notice: 'There are some error.Please try again later.' }
  #           format.json { render :index, status: :created, location: @order }
  #   end
  # end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:product_id,:quantity,:price,:total_price,:status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
     <div class="row">
          <div class="col-xs-4"></div>
              <div class="col-xs-8">
                  <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Product Name *</strong></div>
                          <div class="col-xs-4">
                            <%= f.collection_select(:product_id, Product.all.order("drug_name"), :id, :drug_name, {:prompt => false }, class: "form-control") %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                    <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Quantity *</strong></div>
                          <div class="col-xs-4">
                            <%= f.text_field :quantity, type:"text", class: "form-control", placeholder: 'Enter quantity' , required: "true" %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                      <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Price </strong></div>
                          <div class="col-xs-4">
                            <%= f.text_field :price, type:"text", class: "form-control" , readonly: "true" %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                      <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Total Price *</strong></div>
                          <div class="col-xs-4">
                            <%= f.text_field :total_price, type:"text", class: "form-control", placeholder: 'Total Price' , readonly: "true",required: "true" %>
                            <%= f.hidden_field :status,value: "Unprocessed" %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                    <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"></div>
                          <div class="col-xs-4">
                            <%= f.button "Create", :class => 'btn btn-primary btn-block', id: "submit_btn" %>
                          </div>
                      </div> 
                    </div>
              </div>
       </div>
  
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row" >
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">Listing Sale Orders</strong>
      
  </div>
</div>
<br>
<table class='table table-bordered table-striped table-condensed'>
  <thead>
    <tr>
      <th>Order Id</th>
      <th>Product Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total Price</th>
      <th>Order Date</th>
      <th>Status</th>
      <th>Total sold quantity</th>
      <th>Total sold price</th>
      <th>Reason</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= Product.find(order.product_id).drug_name %></td>
        <td><%= order.quantity %></td>
        <td><%= order.price %></td>
        <td><%= order.total_price %></td>
        <td><%= order.created_at.strftime("%d-%^b-%Y %H-%M-%S") %></td>
        <td><%= order.status %></td>
        <td>
          <% if order.sold_quantity==nil %>
            -
          <% else %>
            <%= order.sold_quantity %>
          <% end %>
        </td>
          <td>
          <% if order.sold_total_price==nil %>
            -
          <% else %>
            <%= order.sold_total_price %>
          <% end %>
        </td>
        <td><% if order.reason==nil %>
              -
            <% else %>
              <%= order.reason %>
            <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div><%= link_to 'New Sale Order', new_order_path, style:"color:green;margin-left:90px"  %></div>
<div><%= link_to 'Process Order', process_order_orders_path, style:"color:green;margin-left:90px"  %></div>

app/views/orders/new.html.erb
<br>
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">New Order</strong>
      
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Back', orders_path, class: "pull-right",style: "margin-right:100px;color:green" %>

<script>
price_fetch();
	$("#order_product_id").change(function(){
		price_fetch();
		
	})
	function price_fetch()
	{
			$.get("/orders/price_fetch",{id : $("#order_product_id").val()},function(data)
			{
				console.log(data)
				if(data.responce=="Success")
				{
					$("#order_price").val(data.product.price);
					if($("#order_quantity").val()!="")
						{
							cal_total_price();
						}
				}
			});
	}
	$("#order_quantity").change(function(){
		cal_total_price();
	});
	function cal_total_price()
	{
		$("#order_total_price").val(parseFloat($("#order_price").val()) * parseFloat($("#order_quantity").val())) ;
	}
</script>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>