config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do
        get 'price_fetch'
        get 'process_order'
      end
    end
  resources :products do
    member do
    get 'mapping'
    post 'mapping_create'
    patch "mapping_create"
  end
end

  resources :categories

  root 'categories#home_page'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json

  def home_page
  end
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :index, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :index, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
      <% end %>
      <div class="row">
          <div class="col-xs-4"></div>
              <div class="col-xs-8">
                  <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Category Name *</strong></div>
                          <div class="col-xs-4">
                            <%= f.text_field :name, type:"text", class: "form-control", placeholder: 'Enter category name' , required: "true" %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                    <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"></div>
                          <div class="col-xs-4">
                            <%= f.button show_text, :class => 'btn btn-primary btn-block', id: "submit_btn" %>
                          </div>
                      </div> 
                    </div>
              </div>
       </div>
    


<!--   <div class="actions">
    <%= f.submit %>
  </div> -->
<% end %>

app/views/categories/edit.html.erb
<br>
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">Editing Category</strong>
      
  </div>
</div>

<%= render 'form', :show_text => "Update" %>

<%= link_to 'Back', categories_path, class: "pull-right",style: "margin-right:100px;color:green" %>

app/views/categories/home_page.html.erb
<h1 style="background-color:blue;margin-top=-1">Sample Inventory Application</h1>
<br>
<div><%= link_to 'Check out our Categories', categories_path,style:"color:green;margin-left:90px" %></div>

<div><%= link_to 'Check out Products ', products_path,style:"color:green;margin-left:90px" %></div>

<div><%= link_to 'Check out Sale order ', orders_path,style:"color:green;margin-left:90px" %></div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row" >
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">Listing Categories</strong>
      
  </div>
</div>
<br>
<table class='table table-bordered table-striped table-condensed' style="margin-left:100px">
  <thead>
    <tr>
      <th colspan='3'>Categories Name</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Edit', edit_category_path(category), style:"color:green" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' },style:"color:green" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div><%= link_to 'Create new Category', new_category_path,style:"color:green;margin-left:90px" %></div>
<br>

app/views/categories/new.html.erb
<br>
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">New Category</strong>
      
  </div>
</div>


<%= render 'form' , :show_text => "Create" %>

<%= link_to 'Back', categories_path, class: "pull-right",style: "margin-right:100px;color:green" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>