config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do
        get 'price_fetch'
        get 'process_order'
      end
    end
  resources :products do
    member do
    get 'mapping'
    post 'mapping_create'
    patch "mapping_create"
  end
end

  resources :categories

  root 'categories#home_page'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_and_belongs_to_many :categories
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @categories=Category.find(params[:category][:id])
    respond_to do |format|
      if @product.save
        @product.categories << @categories
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def mapping
    @product = Product.find(params[:id])
    # @categories=Category.find(params[:category][:id])
  end

  def mapping_create
    @product = Product.find(params[:id])
    @categories=Category.find(params[:category][:id])
    a= Category.joins("join categories_products on categories_products.category_id=categories.id").where("categories_products.product_id = ? and  categories_products.category_id = ?", @product.id,params[:category][:id]) 
   respond_to do |format|
    if a.length>0
     format.html { redirect_to products_path, notice: 'Product was already mapped.' }
        format.json { render :index, status: :created, location: @product }
    else
      @product.categories << @categories
      format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :index, status: :created, location: @product }
    end
  end
  end
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :index, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:drug_name,:quantity,:price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        <div class="row">
          <div class="col-xs-4"></div>
              <div class="col-xs-8">
                  <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Category Name *</strong></div>
                          <div class="col-xs-4">
                             <%= collection_select(:category,:id, Category.all.order("name"), :id, :name, {:prompt => false }, class: "form-control") %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                     <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Product Name *</strong></div>
                          <div class="col-xs-4">
                            <%= f.text_field :drug_name, type:"text", class: "form-control", placeholder: 'Enter Product name' , required: "true" %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                     <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Quantity *</strong></div>
                          <div class="col-xs-4">
                             <%= f.text_field :quantity, type:"text", class: "form-control", placeholder: 'Enter quantity' , required: "true" %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                     <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Category Name *</strong></div>
                          <div class="col-xs-4">
                             <%= f.text_field :price, type:"text", class: "form-control", placeholder: 'Enter price' , required: "true" %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                    <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"></div>
                          <div class="col-xs-4">
                            <%= f.button show_text, :class => 'btn btn-primary btn-block', id: "submit_btn" %>
                          </div>
                      </div> 
                    </div>
              </div>
       </div>

<% end %>

app/views/products/edit.html.erb
<br>
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">Editing Product</strong>
      
  </div>
</div>

<%= render 'form', :show_text => "Update" %>

<%= link_to 'Back', products_path, class: "pull-right",style: "margin-right:100px;color:green" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row" >
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">Listing Products</strong>
      
  </div>
</div>
<br>
<table class='table table-bordered table-striped table-condensed'>
  <thead>
    <tr>

      <th>Product Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th></th>
     
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
       
        <td><%= product.drug_name %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Edit', edit_product_path(product), style:"color:green" %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row" >
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">Mapping of Products</strong>
      
  </div>
</div>
<br>
<table class='table table-bordered table-striped table-condensed'>
  <thead>
    <tr>
     
      <th>Product Name</th>
      <th>Category Name</th>  
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
    <% a= Category.joins("join categories_products on categories_products.category_id=categories.id").where("categories_products.product_id = ? ", product.id) %>
    <tr>
        <td rowspan=<%=a.length %>><%= product.drug_name %></td>
        <% i=0 %>
    <% a.each do |t| %>
    <% if i!=0 %>
      <tr>
    <% end %>
        
        <td><%=  t.name %> </td>
         <% if i==0 %>
        <td rowspan=<%=a.length %>><%= link_to 'Add more categories', mapping_product_path(product), style:"color:green" %></td>
        <% end %>
        <% i=i+1 %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Product', new_product_path, style:"color:green;margin-left:90px" %>

app/views/products/mapping.html.erb
<%= form_for @product, url: {action: "mapping_create", method: "POST"} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        <div class="row">
          <div class="col-xs-4"></div>
              <div class="col-xs-8">
                  <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Category Name *</strong></div>
                          <div class="col-xs-4">
                             <%= collection_select(:category,:id, Category.all.order("name"), :id, :name, {:prompt => false }, class: "form-control") %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
                     <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"><strong>Product Name *</strong></div>
                          <div class="col-xs-4">
                            <%= f.text_field :drug_name, type:"text", class: "form-control", placeholder: 'Enter Product name' , required: "true" , readonly: true %>
                          </div>
                          <div class="col-xs-4"></div>
                      </div> 
                    </div>
           
                    <div class="form-group"> 
                      <div class="row">
                          <div class="col-xs-3"></div>
                          <div class="col-xs-4">
                            <%= f.button "Done", :class => 'btn btn-primary btn-block', id: "submit_btn" %>
                          </div>
                      </div> 
                    </div>
              </div>
       </div>

<% end %>

app/views/products/new.html.erb
<br>
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-10">
    <strong style="font-size:24px">New Product</strong>
      
  </div>
</div>

<%= render 'form', :show_text => "Create" %>

<%= link_to 'Back', products_path, class: "pull-right",style: "margin-right:100px;color:green" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>